#!/usr/bin/perl

my @l = ("+", "-", "0" .. "9", "A" .. "Z", "a" .. "z");
my %l = ();
for ( my $i = 0; $i < @l; $i++) {
    $l{$l[$i]} = $i;    
}

sub b2d {
    my $b = shift;
    my $d = 0;    
    @b = $b =~ /./g;
    my $len_b = @b;
    for ( my $i = 0; $i < $len_b; $i++) {
        $d += 64**($len_b - 1 - $i) * $l{$b[$i]};        
    }
    $d;    
}

while ( <>) {
    print b2d($_), "\n";    
}


