#!/usr/bin/perl

use POSIX qw(ceil);

sub d2b {
    my @l = ("+", "-", "0" .. "9", "A" .. "Z", "a" .. "z");    
    my $d = shift;
    my $b = sprintf "%b", $d;
    
    $b = reverse $b;
    @b = unpack("a6" x ceil((length $b)/6), $b);
    @bb = ();    
    for ( @b) {
        $_ = reverse;
        $_ = oct "0b" . $_;
        $_ = $l[$_];
        unshift @bb, $_;
        
    }
    return join "", @bb;    
}

while ( <>) {
    print d2b($_), "\n";    
}
